version: 0.2

env:
  variables:
    AWS_REGION: eu-north-1
    ECR_REGISTRY: 904233121598.dkr.ecr.eu-north-1.amazonaws.com
    CLUSTER_NAME: TravelEaseCluster
    TF_VAR_FILE: prod.tfvars
  shell: bash

phases:
  install:
    runtime-versions:
      docker: 20
      python: 3.10
    commands:
      - echo "=== Installing prerequisites ==="
      - yum install -y unzip jq
      - echo "Installing Terraform..."
      - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin/
      - terraform -v
      - echo "Login to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  pre_build:
    commands:
      - echo "=== Initializing and applying Terraform ==="
      - cd terraform
      - terraform init -no-color
      - terraform plan -no-color -var-file=../$TF_VAR_FILE -out=tfplan
      - terraform apply -no-color -auto-approve tfplan
      - terraform output -json > ../tf_outputs.json
      - cd ..

      - echo "=== Capturing Terraform Outputs ==="
      - cat tf_outputs.json | jq '.'
      - export ALB_DNS=$(jq -r '.alb_dns_name.value // .load_balancer_dns.value' tf_outputs.json)
      - export S3_BUCKET=$(jq -r '.frontend_bucket_name.value' tf_outputs.json)
      - export FRONTEND_URL=$(jq -r '.frontend_website_url.value' tf_outputs.json)
      - echo "ALB: $ALB_DNS"
      - echo "S3 Bucket: $S3_BUCKET"
      - echo "Frontend: $FRONTEND_URL"

  build:
    commands:
      - echo "=== Building and pushing Docker images to ECR ==="
      - declare -A services=( ["booking-service"]="Booking_Service" ["flight-service"]="Flight_Service" ["payment-service"]="Payment_Service" ["crowdpulse-service"]="CrowdPulse/backend" )
      - for svc in "${!services[@]}"; do
          dir=${services[$svc]};
          echo "Building image for $svc in $dir";
          cd $dir;
          docker build -t $svc .;
          docker tag $svc:latest $ECR_REGISTRY/$svc:latest;
          docker push $ECR_REGISTRY/$svc:latest;
          cd -;
        done

  post_build:
    commands:
      - echo "=== Build Completed Successfully ==="
      - echo "Preparing artifacts for next stage..."
      - echo "ALB_DNS=$ALB_DNS" > deployment_env.txt
      - echo "S3_BUCKET=$S3_BUCKET" >> deployment_env.txt
      - echo "FRONTEND_URL=$FRONTEND_URL" >> deployment_env.txt
      - cat deployment_env.txt

artifacts:
  files:
    - tf_outputs.json
    - deployment_env.txt
  discard-paths: yes
