# File: buildspec.yml (Place this file in the root of your works-praneel/TravelEase_Internship repository)
version: 0.2

# Define environment variables (matching your existing settings)
env:
  variables:
    AWS_REGION: "eu-north-1"
    ECR_REGISTRY: "904233121598.dkr.ecr.eu-north-1.amazonaws.com"
    CLUSTER_NAME: "TravelEaseCluster"
    # This variable correctly targets your nested project folder structure
    REPO_DIR: "works-praneel/travelease_project/TravelEase_Project-239fa85907536e1e224456f82c849cd92624898e"
    # Placeholder for dynamic output.
    ALB_DNS: ""
    S3_BUCKET_NAME: ""
    NEW_ALB_URL: ""
    
phases:
  install:
    commands:
      # Install Terraform and necessary tools, as CodeBuild is a clean environment
      - echo Installing dependencies...
      - apt-get update && apt-get install -y unzip curl
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      
  pre_build:
    commands:
      # AWS CLI is pre-installed. Credentials are handled by the CodeBuild IAM role.
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      
  build:
    commands:
      # --- 1. Apply Infrastructure (Terraform) ---
      - echo Running Terraform init and apply...
      - cd $REPO_DIR/terraform
      - terraform init
      - terraform apply -auto-approve
      
      # Capture Terraform outputs into shell variables
      - export ALB_DNS=$(terraform output -raw load_balancer_dns)
      - export S3_BUCKET_NAME=$(terraform output -raw frontend_bucket_name)
      - export NEW_ALB_URL="http://$ALB_DNS"
      - echo "Captured ALB DNS: $ALB_DNS"
      - echo "Captured S3 Bucket: $S3_BUCKET_NAME"

      # --- 2. Update index.html (using sed for Linux environment) ---
      - echo Updating ALB URL in index.html...
      - cd ../.. # Go back to the CodeBuild root directory
      # sed -i is used for in-place editing. The delimiters are changed to | to handle / in the URL.
      - sed -i "s|const ALB_URL = \".*\"|const ALB_URL = \"$NEW_ALB_URL\";|" $REPO_DIR/index.html
      - sed -i "s|const API_ENDPOINT = \".*\"|const API_ENDPOINT = \"$NEW_ALB_URL\";|" $REPO_DIR/index.html

      # --- 3. Build, Tag, and Push Images ---
      - echo Building and pushing Docker images...
      - SERVICE_DIRS=("Flight_Service" "Booking_Service" "Payment_Service" "CrowdPulse/backend")
      - SERVICE_NAMES=("flight-service" "booking-service" "payment-service" "crowdpulse-service")
      
      - for i in "${!SERVICE_DIRS[@]}"; do
          DIR_PATH=${SERVICE_DIRS[i]}
          SERVICE_NAME=${SERVICE_NAMES[i]}
          
          echo "Building and pushing $SERVICE_NAME"
          docker build -t $SERVICE_NAME $REPO_DIR/$DIR_PATH
          docker tag $SERVICE_NAME:latest $ECR_REGISTRY/$SERVICE_NAME:latest
          docker push $ECR_REGISTRY/$SERVICE_NAME:latest
        done

      # --- 4. Deploy to Fargate (Force new deployment) ---
      - echo Force deploying ECS services...
      - for SERVICE in "${SERVICE_NAMES[@]}"; do
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE --force-new-deployment
        done
        
      # --- 5. Deploy Frontend Files to S3 ---
      - echo Deploying frontend assets to S3...
      # Use the dynamically captured $S3_BUCKET_NAME
      - aws s3 cp $REPO_DIR/index.html s3://$S3_BUCKET_NAME/index.html --content-type text/html --acl public-read
      - aws s3 cp $REPO_DIR/CrowdPulse/frontend/crowdpulse_widget.html s3://$S3_BUCKET_NAME/crowdpulse_widget.html --content-type text/html --acl public-read
      - aws s3 cp $REPO_DIR/images/travelease_logo.png s3://$S3_BUCKET_NAME/images/travelease_logo.png --content-type image/png --acl public-read